### PR TITLE
Adding terraform module to provision Prometheus and Grafana

### PR DESCRIPTION
**Pull request by dunchych**
This module was tested on OCP 4.3 only and relies on OLM.
The additional info on how this module works is here https://github.ibm.com/yaroslav/liberty-day2

### CODE REVIEW

**Comment by dunchych** [comment]
Hi @csantanapr, I checked in requested chages to the branch.  Few clarifications:
1. I had to create DIY `yaml/rbac.yaml` as operator-provided rbac objects only partially worked, will revisit in the future 
2. In all *.sh
Use in all oc commands` -s ${NAMESPACE}`. >>>> not sure what -s means here? use `-n`

**Comment by csantanapr** [comment]
I was using the Prometheus and agrada a operator this week for a think2020 demo and I got it working with no need to create any rbac resources 

We should double check on that

**Comment by csantanapr** [comment]
You need to add “-n $NAMESPACR” for all oc commands on destroy and create, there a few places you don’t specify the tools namespace

**Comment by dunchych** [comment]
Hi @csantanapr,  I cleaned up all missing -n's 
For rbac, I tried again, the default rbac generated by the operator does not work  for a specific scenario I want to use with prometheus where the servicemonitors point to a different namespace.  If I dont bind prometheus service acct to a custom cluster role it does not detect endpoints in other namespaces

**Comment by csantanapr** [comment]
@dunchych You are correct I tested and saw the kabanero guide
https://kabanero.io/guides/app-monitoring-ocp4.2/

We want to have the rbac ClusterRole created for prometheus to be able to scrape any pod on any namespace, even if the ServiceMonitor or PodMonitor are all located in the `tools` namespace

**Pull request merged**
